<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user') ?>

    <!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <br><br>
            <article class="col-xs-12 maincontent">
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h3 class="thin text-center">Os seus dados</h3>
                            <hr>
        
                        </div>
                    </div>
                </div>
            </article>
            <!-- /Article -->
        </div>
    </div>	<!-- /container -->