<?php use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;

Layout::includeLayout('header');
$list_all_users = Data::get("all_users");
?>
<!-- container -->
<div class="container">
	<h2>Administração</h2>
	<hr>
	<table id="admin">
		<tr>
			<th>Name</th>
			<th>Username</th>
			<th>Email</th>
			<th>Bloqueado</th>
		</tr>
		<?php foreach ($list_all_users as $user) { ?>
			<tr>
				<td style="width:30%;"><?= $user->name ?></td>
				<td style="width:20%;"><?= $user->username ?></td>
				<td style="width:30%;"><?= $user->email ?></td>
				<?php if ($user->blocked == 0) {?>
					<td style="width:20%;"><a style="width:100%;" class="btn btn-action" role="button" href="<?= Url::toRoute('admin/blockUser', $user->id)?>">Bloquear</a></td>
				<?php } else { ?>
					<td style="width:20%;"><a style="width:100%;"class="btn btn-action" role="button" href="<?= Url::toRoute('admin/blockUser', $user->id)?>">Desbloquear</a></td>
				<?php } ?>
			</tr>
		<?php } ?>
	</table>
</div>	
<!-- /container -->