<?php
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Session;
use ArmoredCore\WebObjects\Asset;

Layout::includeLayout('header');
$game = Data::get('game');
?>

<div class="container">
    <div class="gameTable">
        <div class="player">
            <div class="playerNumbers">
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 1)?>">1</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 2)?>">2</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 3)?>">3</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 4)?>">4</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 5)?>">5</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 6)?>">6</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 7)?>">7</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 8)?>">8</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 9)?>">9</a>
                <img src="/weblogicmvc/public/img/user.png">
            </div>
            <div class="playerPoints">
                <p>&nbsp;</p>
            </div>
        </div>
        <div class="dices">
            <?php echo '<img src="' . Asset::image($game->_resultDice1 . '.png') . '">'; ?>
            <?php echo '<img src="' . Asset::image($game->_resultDice2 . '.png') . '">'; ?>
        </div>
        <?php if (!Session::has('game')){?>
            <a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('game/startGame')?>">Começar jogo</a>
        <?php } else {?>              
            <a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('game/throwDices')?>">Lançar dados</a>
        <?php } ?>
        <div class="bot">
            <div class="botPoints">
                <p>&nbsp;</p>
            </div>
            <div class="botNumbers">
                <img src="/weblogicmvc/public/img/bot.png">
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 1)?>">1</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 2)?>">2</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 3)?>">3</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 4)?>">4</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 5)?>">5</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 6)?>">6</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 7)?>">7</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 8)?>">8</a>
                <a class="btn btn-action" role="button" href="<?= Url::toRoute('game/blockNumber', 9)?>">9</a>
            </div>
        </div>
    </div>
</div>