<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
Layout::includeLayout('indexheader'); ?>
    <header id="head">
        <div class="container">
            <div class="row">
                <h1 class="lead"><b>Shut the Box</b></h1>
                <br><br>
                <p><a class="btn btn-action btn-lg" role="button" href="<?= Url::toRoute('game/index')?>">JOGAR AGORA</a>
            </div>
        </div>
    </header>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1440 320"><path fill="#131315" fill-opacity="1" d="M0,96L26.7,128C53.3,160,107,224,160,240C213.3,256,267,224,320,213.3C373.3,203,427,213,480,229.3C533.3,245,587,267,640,261.3C693.3,256,747,224,800,224C853.3,224,907,256,960,245.3C1013.3,235,1067,181,1120,170.7C1173.3,160,1227,192,1280,213.3C1333.3,235,1387,245,1413,250.7L1440,256L1440,0L1413.3,0C1386.7,0,1333,0,1280,0C1226.7,0,1173,0,1120,0C1066.7,0,1013,0,960,0C906.7,0,853,0,800,0C746.7,0,693,0,640,0C586.7,0,533,0,480,0C426.7,0,373,0,320,0C266.7,0,213,0,160,0C106.7,0,53,0,27,0L0,0Z"></path></svg>
    <div class="container" style="margin-top: 100px;">
        <div class="row text-center">
            <div class="col-md-6">
                <div class="icon">
                    <img src="https://cdn.iconscout.com/icon/premium/png-512-thumb/dice-1959008-1652828.png" style="max-width: 40%; margin-bottom: 30px;">
                </div>          
                <h1>Regras</h1>
                <hr style="margin-bottom: 20px; width: 70px; border-top: 2px solid #e95420; margin-top: 10px;">
                <p>
                    O jogador joga repetidamente os dados e bloqueia o número ou os números a cada lançamento.
                    Isto mantém-se até que não seja possível bloquear nenhum número de acordo com o valor dos
                    dados lançados. Assim dá-se por concluído o jogo para o jogador atual.
                </p>
            </div>
            <div class="col-md-6">
                <div class="icon">
                    <img src="https://boardgamegander.uk/assets/images/logo-sanstext.png" style="max-width: 40%; padding: 16px 0 0 0; margin-bottom: 30px; vertical-align: text-top;">
                </div>          
                <h1>Objetivo</h1>
                <hr style="margin-bottom: 20px; width: 70px; border-top: 2px solid #e95420; margin-top: 10px;">
                <p>
                    O Shut the Box tem como objetivo fechar (bloquear) todos os números do tabuleiro, utilizando
                    os dois dados de 6 faces numeradas. Para tal, o jogador deve lançar os dois dados e ao valor
                    obtido deve bloquear qualquer número de peças do tabuleiro que no seu conjunto perfaçam a
                    soma do resultado do lançamento dos dois dados.
                </p>
            </div>
        </div> 
    </div>

    <!---------------Skills-------------------->
    <section id="skills" style="background: #131315; color:#ccc; padding: 0 0 50px 0; margin-top: 150px;">
    <h1 class="text-center" style="color: white; margin:0 0 0 0; padding:50px 0 10px 0;">PROJETO ELABORADO POR:</h1>
    <hr style="width: 150px; border-top: 2px solid #e95420; margin-top:0px; margin-bottom:40px;">
        <div class="container">
            <div class="row text-center">
                <div class="col-md-6">
                    <div class="icon">
                        <img src="https://www.cicloleiriense.com.br/wp-content/uploads/2015/06/joe-dawson.png" style="max-width: 40%; padding: 16px 0 0 0;">
                    </div>          
                    <h2>Bruno Correia</h2>
                    <p style="color:#e95420;">Nº 210000</p>
                </div>
                <div class="col-md-6">
                    <div class="icon">
                        <img src="https://lh3.googleusercontent.com/proxy/TZRqGv_6nWHgib6nGwWn0dtsLd5ysyS_A9t8JeyGh1tiITURo2tF5DgthuMXFeG9wuXJD6-Y9Zwk_hBem9621P_S5r_Io2-uzYr4JsOYKPYr" style="max-width: 40%; padding: 16px 0 0 0;">
                    </div>          
                    <h2>Martim Silva</h2>
                    <p style="color:#e95420;">Nº 2180686</p>
                </div>
            </div> 
        </div>
    </section>
</div>	