<?php 
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\URL;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\ErrMgr;

Layout::includeLayout('header') ?>
<?php $user = Data::get('user')?>
<?php ErrMgr::attach($user) ?>

	<!-- container -->
    <div class="container">
        <div class="row">
            <!-- Article main content -->
            <article class="col-xs-12 maincontent">
                <br><br>
                <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                    <div class="panel panel-default">
                        <div class="panel-body">
                            <h1 class="thin text-center">Criar Conta</h1>
                            <hr>
							<form action="<?= URL::toRoute('home/signup') ?>" method="Post">
                                <div class="top-margin">
                                    <label>Name <span class="text-danger">*</span></label>
                                    <input required type="text" value="<?= $user->name ?>" class="form-control" name="name" placeholder="Insira um nome">
                                    <?php echo(ErrMgr::bind('name')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Username <span class="text-danger">*</span></label>
                                    <input required type="text" value="<?= $user->username ?>" class="form-control" name="username" placeholder="Insira um username">
                                    <?php echo(ErrMgr::bind('username')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Email <span class="text-danger">*</span></label>
                                    <input required type="email" value="<?= $user->email ?>" class="form-control" name="email" placeholder="Insira um email">
                                    <?php echo(ErrMgr::bind('email')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Password <span class="text-danger">*</span></label>
                                    <input required type="password" value="<?= $user->password ?>" class="form-control" name="password" placeholder="Insira uma password">
                                    <?php echo(ErrMgr::bind('password')) ?>
                                </div>
                                <div class="top-margin">
                                    <label>Birthdate <span class="text-danger">*</span></label>
                                    <input required type="date" class="form-control" name="birthdate">
                                </div>
                                <hr>
                                <div class="row">
                                    <div class="col-lg-8 text-right">
                                        <button class="btn btn-action"  type="submit">Registar</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
            <!-- /Article -->

        </div>
    </div>	<!-- /container -->