<?php
use ArmoredCore\WebObjects\Asset;
use ArmoredCore\WebObjects\Layout;
use ArmoredCore\WebObjects\Data;
use ArmoredCore\WebObjects\Session;

Layout::includeLayout('header');
$leaderboard = Data::get("leaderboard");
?>

<div class="container">
    <div class="row">
        <!-- Article main content -->
        <article class="col-xs-12 maincontent">
            <header class="page-header">
                <h1 class="page-title">TOP 10</h1>
            </header>
            <div class="col-md-6 col-md-offset-3 col-sm-8 col-sm-offset-2">
                <table class="table table-hover">
                    <tr>
                        <th style="text-align:center;">#</th>
                        <th style="text-align:center;">Username</th>
                        <th style="text-align:center;">Pontos</th>
                        <th style="text-align:center;">Data</th>
                    </tr>
                    <?php $i = 1; ?>
                    <?php foreach ($leaderboard as $classification) { ?>
                        <?php if(isset($_SESSION['userid']) && $_SESSION['userid'] == $classification->user_id) {?>
                        <tr style="background-color: beige;">
                            <th style="width:5%; text-align:center;"><?= $i++ ?></th>
                            <th style="width:20%; text-align:center;"><?= $classification->username ?></th>
                            <th style="width:15%; text-align:center;"><?= $classification->points ?></th>
                            <th style="width:20%; text-align:center;"><?= $classification->date ?>h</th>
                        </tr>
                        <?php } else { ?>
                            <tr>
                            <th style="width:5%; text-align:center;"><?= $i++ ?></th>
                            <th style="width:20%; text-align:center;"><?= $classification->username ?></th>
                            <th style="width:15%; text-align:center;"><?= $classification->points ?></th>
                            <th style="width:20%; text-align:center;"><?= $classification->date ?>h</th>
                        </tr>
                        <?php } ?>
                    <?php } ?>
                </table>
            </div>
        </article>
        <!-- /Article -->
    </div>
</div>
